app_name = "ndis_crm"
app_title = "NDIS CRM"
app_publisher = "Hex Flow"
app_description = "Custom NDIS CRM app for ERPNext"
app_email = "info@hexflow.com.au"
app_license = "mit"

# Installation
# ------------
after_install = "ndis_crm.setup.foundation.after_install"

# Fixtures
# --------
# Keep these lists consolidated. `bench export-fixtures` uses these scopes to
# recreate the CRM fields, statuses, scripts, and setup records in new sites.

CUSTOM_FIELD_FIXTURE_DOCTYPES = ['CRM Deal',
 'CRM Lead',
 'Lead',
 'Opportunity',
 'Communication',
 'NDIS CRM Actual Remittance Import Run',
 'NDIS CRM Attendance Draft',
 'NDIS CRM Billing Draft',
 'NDIS CRM Care Management Integration Run',
 'NDIS CRM Claim Batch Draft Run',
 'NDIS CRM Claim Batch Submission Run',
 'NDIS CRM Claim Draft',
 'NDIS CRM Claim Export Preparation Run',
 'NDIS CRM Claim Lodgement Confirmation Run',
 'NDIS CRM Downstream Preparation',
 'NDIS CRM Finance Onboarding',
 'NDIS CRM Handover',
 'NDIS CRM Invoice Draft',
 'NDIS CRM Operational Dashboard Snapshot Run',
 'NDIS CRM Operations Setup',
 'NDIS CRM Payment Allocation Preparation Run',
 'NDIS CRM Payment Entry Draft Run',
 'NDIS CRM Payment Entry Submission Run',
 'NDIS CRM Permission Workflow Hardening Run',
 'NDIS CRM Post Closure Routing Finalisation Run',
 'NDIS CRM Post Closure Routing Preparation Run',
 'NDIS CRM Recovery Case Draft Run',
 'NDIS CRM Recovery Case Submission Run',
 'NDIS CRM Recovery Communication Dispatch Run',
 'NDIS CRM Recovery Communication Draft Creation Run',
 'NDIS CRM Recovery Communication Draft Preparation Run',
 'NDIS CRM Recovery Communication Outcome Capture Run',
 'NDIS CRM Recovery Follow Up Preparation Run',
 'NDIS CRM Recovery Follow Up Task Activation Run',
 'NDIS CRM Recovery Follow Up Task Draft Run',
 'NDIS CRM Recovery Outcome Action Activation Run',
 'NDIS CRM Recovery Outcome Action Completion Run',
 'NDIS CRM Recovery Outcome Action Draft Run',
 'NDIS CRM Recovery Outcome Action Preparation Run',
 'NDIS CRM Recovery Outcome Closure Draft Run',
 'NDIS CRM Recovery Outcome Closure Finalisation Run',
 'NDIS CRM Recovery Outcome Closure Preparation Run',
 'NDIS CRM Recovery Preparation Run',
 'NDIS CRM Remittance Import Finalisation Run',
 'NDIS CRM Remittance Import Preparation Run',
 'NDIS CRM Remittance Matching Review Run',
 'NDIS CRM Roster Build Request',
 'NDIS CRM Sales Invoice Draft Run',
 'NDIS CRM Sales Invoice Submission Run',
 'NDIS CRM Service Delivery Evidence Review',
 'NDIS CRM Service Schedule Draft',
 'NDIS CRM Service Session Draft',
 'NDIS CRM UAT Regression Evidence Pack Run',
 'NDIS CRM Variance Rejection Review Run',
 'NDIS CRM Write Off Draft Run',
 'NDIS CRM Write Off Finalisation Run',
 'NDIS CRM Write Off JE Draft Run',
 'NDIS CRM Write Off JE Submission Run',
 'NDIS CRM Write Off Preparation Run',
 'NDIS Participant Intake',
 'NDIS Participant Service File',
 'Task',
 'ToDo']

CLIENT_SCRIPT_FIXTURES = ['NDIS CRM Post Closure Routing Finalisation Phase56 Actions',
 'NDIS CRM Care Management Integration Run Actions',
 'NDIS CRM Post Closure Routing Preparation Phase55 Actions',
 'NDIS CRM Post Closure Routing Finalisation Run Actions',
 'NDIS CRM Recovery Outcome Closure Finalisation Phase54 Actions',
 'NDIS CRM Post Closure Routing Preparation Run Actions',
 'NDIS CRM Recovery Outcome Closure Draft Phase53 Actions',
 'NDIS CRM Recovery Outcome Closure Finalisation Run Actions',
 'NDIS CRM Recovery Outcome Closure Preparation Phase52 Actions',
 'NDIS CRM Recovery Outcome Closure Draft Run Actions',
 'NDIS CRM Recovery Outcome Action Completion Phase51 Actions',
 'NDIS CRM Recovery Outcome Closure Preparation Run Actions',
 'NDIS CRM Recovery Outcome Action Activation Phase50 Actions',
 'NDIS CRM Recovery Outcome Action Completion Run Actions',
 'NDIS CRM Recovery Outcome Action Draft Phase49 Actions',
 'NDIS CRM Recovery Outcome Action Activation Run Actions',
 'NDIS CRM Recovery Outcome Action Preparation Phase48 Actions',
 'NDIS CRM Recovery Outcome Action Draft Run Actions',
 'NDIS CRM Recovery Communication Outcome Capture Phase47 Actions',
 'NDIS CRM Recovery Outcome Action Preparation Run Actions',
 'NDIS CRM Recovery Communication Dispatch Phase46 Actions',
 'NDIS CRM Recovery Communication Outcome Capture Run Actions',
 'NDIS CRM Recovery Communication Draft Creation Phase45 Actions',
 'NDIS CRM Recovery Communication Dispatch Run Actions',
 'NDIS CRM Recovery Communication Draft Preparation Phase44 Actions',
 'NDIS CRM Recovery Communication Draft Creation Run Actions',
 'NDIS CRM Recovery Follow Up Task Activation Phase43 Actions',
 'NDIS CRM Recovery Communication Draft Preparation Run Actions',
 'NDIS CRM Recovery Follow Up Task Draft Phase42 Actions',
 'NDIS CRM Recovery Follow Up Task Activation Run Actions',
 'NDIS CRM Recovery Follow Up Preparation Phase41 Actions',
 'NDIS CRM Recovery Follow Up Task Draft Run Actions',
 'NDIS CRM Recovery Case Submission Phase40 Actions',
 'NDIS CRM Recovery Follow Up Preparation Run Actions',
 'NDIS CRM Recovery Case Draft Phase39 Actions',
 'NDIS CRM Recovery Case Submission Run Actions',
 'NDIS CRM Recovery Preparation Phase38 Actions',
 'NDIS CRM Recovery Case Draft Run Actions',
 'NDIS CRM Variance Review Phase37 Recovery Actions',
 'NDIS CRM Write Off Finalisation Phase37 Actions',
 'NDIS CRM Recovery Preparation Run Actions',
 'NDIS CRM Write Off JE Submission Phase36 Actions',
 'NDIS CRM Write Off Finalisation Run Actions',
 'NDIS CRM Write Off JE Draft Phase35 Actions',
 'NDIS CRM Write Off JE Submission Run Actions',
 'NDIS CRM Write Off Draft Phase34 Actions',
 'NDIS CRM Write Off JE Draft Run Actions',
 'NDIS CRM Write Off Preparation Phase33 Actions',
 'NDIS CRM Write Off Draft Run Actions',
 'NDIS CRM Variance Review Phase32 Actions',
 'NDIS CRM Write Off Preparation Run Actions',
 'NDIS CRM Variance Rejection Review Run Actions',
 'NDIS CRM Remittance Import Finalisation Run Actions',
 'NDIS CRM Payment Entry Submission Run Actions',
 'NDIS CRM Payment Entry Draft Run Actions',
 'NDIS CRM Payment Allocation Preparation Run Actions',
 'NDIS CRM Remittance Matching Review Run Actions',
 'NDIS CRM Actual Remittance Import Run Actions',
 'NDIS CRM Remittance Import Preparation Run Actions',
 'NDIS CRM Claim Lodgement Confirmation Run Actions',
 'NDIS CRM Claim Export Preparation Run Actions',
 'NDIS CRM Claim Batch Submission Run Actions',
 'NDIS CRM Claim Batch Draft Run Actions',
 'NDIS CRM Sales Invoice Submission Run Actions',
 'NDIS CRM Sales Invoice Draft Run Actions',
 'NDIS CRM Invoice Draft Actions',
 'NDIS CRM Claim Draft Actions',
 'NDIS CRM Billing Draft Actions',
 'NDIS CRM Attendance Draft Actions',
 'NDIS CRM Downstream Preparation Actions',
 'NDIS CRM Service Delivery Evidence Review Actions',
 'NDIS CRM Service Session Draft Actions',
 'NDIS Participant Service File Actions',
 'NDIS CRM Roster Build Request Actions',
 'NDIS CRM Service Schedule Draft Actions',
 'NDIS CRM Operations Setup Actions',
 'NDIS Participant Intake Actions',
 'NDIS CRM Finance Onboarding Actions',
 'NDIS CRM Handover Actions',
 'NDIS CRM Care Management Integration Phase57 Actions',
 'NDIS CRM Operational Dashboard Snapshot Run Actions',
 'NDIS CRM Operational Dashboard Phase58 Actions',
 'NDIS CRM Permission Workflow Hardening Run Actions',
 'NDIS CRM Permission Workflow Hardening Phase59 Actions',
 'NDIS CRM UAT Regression Evidence Pack Run Actions',
 'NDIS CRM UAT Regression Evidence Phase60 Actions',
 'NDIS CRM Production Readiness Freeze Run Actions']

CRM_LEAD_STATUSES = ['New Enquiry',
 'Contact Attempted',
 'Contacted',
 'Intake Started',
 'Waiting Documents',
 'Funding / Suitability Review',
 'Qualified',
 'Converted',
 'Not Suitable',
 'No Response',
 'Duplicate',
 'Declined by Participant',
 'No Funding',
 'Provider Capacity Issue']

CRM_DEAL_STATUSES = ['New Opportunity',
 'Service Need Confirmed',
 'Documents Requested',
 'Documents Collected',
 'Funding Verified',
 'Service Agreement Sent',
 'Service Agreement Signed',
 'Handover to Operations',
 'Won / Active Client',
 'Lost']

NDIS_CRM_ROLES = ['NDIS CRM Manager',
 'NDIS Intake Officer',
 'NDIS Service Manager',
 'NDIS Plan Management Officer',
 'NDIS CRM Read Only']

fixtures = [
    {
        "doctype": "Custom Field",
        "filters": [["dt", "in", CUSTOM_FIELD_FIXTURE_DOCTYPES]],
    },
    {
        "doctype": "CRM Form Script",
        "filters": [["name", "in", ["NDIS CRM Deal Actions"]]],
    },
    {
        "doctype": "Client Script",
        "filters": [["name", "in", CLIENT_SCRIPT_FIXTURES]],
    },
    {
        "doctype": "CRM Lead Status",
        "filters": [["name", "in", CRM_LEAD_STATUSES]],
    },
    {
        "doctype": "CRM Deal Status",
        "filters": [["name", "in", CRM_DEAL_STATUSES]],
    },
    {
        "doctype": "Role",
        "filters": [["name", "in", NDIS_CRM_ROLES]],
    },
    {
        "doctype": "Workspace",
        "filters": [["name", "in", ["NDIS CRM"]]],
    },
    {
        "doctype": "Desktop Icon",
        "filters": [["app", "=", "ndis_crm"]],
    },
    {"doctype": "NDIS Document Type"},
    {"doctype": "NDIS Service Document Rule"},
]

# Document Events
# ---------------
# CRM Deal validation is intentionally routed through the latest combined
# validator. Supporting Run DocTypes keep their own validate/on_update hooks.

doc_events = {'CRM Lead': {'validate': 'ndis_crm.phase2_api.validate_crm_lead'},
 'CRM Deal': {'validate': 'ndis_crm.phase60_production_readiness_freeze.validate_crm_deal_phase60_combined'},
 'NDIS Participant Intake': {'validate': 'ndis_crm.phase2_api.validate_intake'},
 'NDIS CRM Recovery Outcome Closure Finalisation Run': {'validate': 'ndis_crm.phase53_recovery_outcome_closure_finalisation.validate_recovery_outcome_closure_finalisation_run',
                                                        'on_update': 'ndis_crm.phase53_recovery_outcome_closure_finalisation.on_recovery_outcome_closure_finalisation_run_update'},
 'NDIS CRM Post Closure Routing Preparation Run': {'validate': 'ndis_crm.phase54_recovery_outcome_post_closure_routing_preparation.validate_post_closure_routing_preparation_run',
                                                   'on_update': 'ndis_crm.phase54_recovery_outcome_post_closure_routing_preparation.on_post_closure_routing_preparation_run_update'},
 'NDIS Document Request': {'after_insert': 'ndis_crm.phase3_documents.on_document_request_update',
                           'on_update': 'ndis_crm.phase3_documents.on_document_request_update'},
 'NDIS CRM Handover': {'validate': 'ndis_crm.phase4_handover.validate_handover',
                       'on_update': 'ndis_crm.phase4_handover.on_handover_update'},
 'NDIS CRM Finance Onboarding': {'validate': 'ndis_crm.phase6_finance_drafts.validate_finance_onboarding_phase6_combined',
                                 'on_update': 'ndis_crm.phase6_finance_drafts.on_finance_onboarding_phase6_update'},
 'NDIS CRM Operations Setup': {'validate': 'ndis_crm.phase7_operations_setup.validate_operations_setup',
                               'on_update': 'ndis_crm.phase7_operations_setup.on_operations_setup_update'},
 'NDIS CRM Service Schedule Draft': {'validate': 'ndis_crm.phase8_service_schedule.validate_schedule_draft',
                                     'on_update': 'ndis_crm.phase8_service_schedule.on_schedule_draft_update'},
 'NDIS CRM Roster Build Request': {'validate': 'ndis_crm.phase9_roster_build_request.validate_roster_build_request',
                                   'on_update': 'ndis_crm.phase9_roster_build_request.on_roster_build_request_update'},
 'NDIS Participant Service File': {'validate': 'ndis_crm.phase10_service_file.validate_service_file',
                                   'on_update': 'ndis_crm.phase10_service_file.on_service_file_update'},
 'NDIS CRM Service Session Draft': {'validate': 'ndis_crm.phase11_service_sessions.validate_session_draft',
                                    'on_update': 'ndis_crm.phase11_service_sessions.on_session_draft_update'},
 'NDIS CRM Service Delivery Evidence Review': {'validate': 'ndis_crm.phase12_delivery_evidence.validate_evidence_review',
                                               'on_update': 'ndis_crm.phase12_delivery_evidence.on_evidence_review_update'},
 'NDIS CRM Downstream Preparation': {'validate': 'ndis_crm.phase13_downstream_preparation.validate_downstream_preparation',
                                     'on_update': 'ndis_crm.phase13_downstream_preparation.on_downstream_preparation_update'},
 'NDIS CRM Attendance Draft': {'validate': 'ndis_crm.phase14_attendance_draft.validate_attendance_draft',
                               'on_update': 'ndis_crm.phase14_attendance_draft.on_attendance_draft_update'},
 'NDIS CRM Billing Draft': {'validate': 'ndis_crm.phase15_billing_draft.validate_billing_draft',
                            'on_update': 'ndis_crm.phase15_billing_draft.on_billing_draft_update'},
 'NDIS CRM Claim Draft': {'validate': 'ndis_crm.phase16_claim_draft.validate_claim_draft',
                          'on_update': 'ndis_crm.phase16_claim_draft.on_claim_draft_update'},
 'NDIS CRM Invoice Draft': {'validate': 'ndis_crm.phase17_invoice_draft.validate_invoice_draft',
                            'on_update': 'ndis_crm.phase17_invoice_draft.on_invoice_draft_update'},
 'NDIS CRM Sales Invoice Draft Run': {'validate': 'ndis_crm.phase18_sales_invoice_draft.validate_sales_invoice_draft_run',
                                      'on_update': 'ndis_crm.phase18_sales_invoice_draft.on_sales_invoice_draft_run_update'},
 'NDIS CRM Sales Invoice Submission Run': {'validate': 'ndis_crm.phase19_sales_invoice_submission.validate_sales_invoice_submission_run',
                                           'on_update': 'ndis_crm.phase19_sales_invoice_submission.on_sales_invoice_submission_run_update'},
 'NDIS CRM Claim Batch Draft Run': {'validate': 'ndis_crm.phase20_claim_batch_draft.validate_claim_batch_draft_run',
                                    'on_update': 'ndis_crm.phase20_claim_batch_draft.on_claim_batch_draft_run_update'},
 'NDIS CRM Claim Batch Submission Run': {'validate': 'ndis_crm.phase21_claim_batch_submission.validate_claim_batch_submission_run',
                                         'on_update': 'ndis_crm.phase21_claim_batch_submission.on_claim_batch_submission_run_update'},
 'NDIS CRM Claim Export Preparation Run': {'validate': 'ndis_crm.phase22_claim_export_preparation.validate_claim_export_preparation_run',
                                           'on_update': 'ndis_crm.phase22_claim_export_preparation.on_claim_export_preparation_run_update'},
 'NDIS CRM Claim Lodgement Confirmation Run': {'validate': 'ndis_crm.phase23_claim_lodgement_confirmation.validate_claim_lodgement_confirmation_run',
                                               'on_update': 'ndis_crm.phase23_claim_lodgement_confirmation.on_claim_lodgement_confirmation_run_update'},
 'NDIS CRM Remittance Import Preparation Run': {'validate': 'ndis_crm.phase24_remittance_import_preparation.validate_remittance_import_preparation_run',
                                                'on_update': 'ndis_crm.phase24_remittance_import_preparation.on_remittance_import_preparation_run_update'},
 'NDIS CRM Actual Remittance Import Run': {'validate': 'ndis_crm.phase25_actual_remittance_import.validate_actual_remittance_import_run',
                                           'on_update': 'ndis_crm.phase25_actual_remittance_import.on_actual_remittance_import_run_update'},
 'NDIS CRM Remittance Matching Review Run': {'validate': 'ndis_crm.phase26_remittance_matching_review.validate_remittance_matching_review_run',
                                             'on_update': 'ndis_crm.phase26_remittance_matching_review.on_remittance_matching_review_run_update'},
 'NDIS CRM Payment Allocation Preparation Run': {'validate': 'ndis_crm.phase27_payment_allocation_preparation.validate_payment_allocation_preparation_run',
                                                 'on_update': 'ndis_crm.phase27_payment_allocation_preparation.on_payment_allocation_preparation_run_update'},
 'NDIS CRM Payment Entry Draft Run': {'validate': 'ndis_crm.phase28_payment_entry_draft.validate_payment_entry_draft_run',
                                      'on_update': 'ndis_crm.phase28_payment_entry_draft.on_payment_entry_draft_run_update'},
 'Payment Entry': {'before_submit': 'ndis_crm.phase29_payment_entry_submission.validate_payment_entry_phase29_submit_guard'},
 'NDIS CRM Payment Entry Submission Run': {'validate': 'ndis_crm.phase29_payment_entry_submission.validate_payment_entry_submission_run',
                                           'on_update': 'ndis_crm.phase29_payment_entry_submission.on_payment_entry_submission_run_update'},
 'NDIS CRM Remittance Import Finalisation Run': {'validate': 'ndis_crm.phase30_remittance_import_finalisation.validate_remittance_import_finalisation_run',
                                                 'on_update': 'ndis_crm.phase30_remittance_import_finalisation.on_remittance_import_finalisation_run_update'},
 'NDIS Remittance Import': {'before_submit': 'ndis_crm.phase30_remittance_import_finalisation.validate_remittance_import_phase30_submit_guard'},
 'NDIS CRM Variance Rejection Review Run': {'validate': 'ndis_crm.phase31_variance_rejection_review.validate_variance_rejection_review_run',
                                            'on_update': 'ndis_crm.phase31_variance_rejection_review.on_variance_rejection_review_run_update'},
 'NDIS CRM Write Off Preparation Run': {'validate': 'ndis_crm.phase32_write_off_preparation.validate_write_off_preparation_run',
                                        'on_update': 'ndis_crm.phase32_write_off_preparation.on_write_off_preparation_run_update'},
 'NDIS CRM Write Off Draft Run': {'validate': 'ndis_crm.phase33_write_off_draft.validate_write_off_draft_run',
                                  'on_update': 'ndis_crm.phase33_write_off_draft.on_write_off_draft_run_update'},
 'NDIS Write Off': {'before_submit': 'ndis_crm.phase33_write_off_draft.validate_optional_ndis_write_off_phase33_submit_guard'},
 'NDIS CRM Write Off JE Draft Run': {'validate': 'ndis_crm.phase34_write_off_je_draft.validate_write_off_je_draft_run',
                                     'on_update': 'ndis_crm.phase34_write_off_je_draft.on_write_off_je_draft_run_update'},
 'Journal Entry': {'before_submit': 'ndis_crm.phase35_write_off_je_submission.validate_journal_entry_phase35_submit_guard'},
 'NDIS CRM Write Off JE Submission Run': {'validate': 'ndis_crm.phase35_write_off_je_submission.validate_write_off_je_submission_run',
                                          'on_update': 'ndis_crm.phase35_write_off_je_submission.on_write_off_je_submission_run_update'},
 'NDIS CRM Write Off Finalisation Run': {'validate': 'ndis_crm.phase36_write_off_finalisation.validate_write_off_finalisation_run',
                                         'on_update': 'ndis_crm.phase36_write_off_finalisation.on_write_off_finalisation_run_update'},
 'NDIS CRM Recovery Preparation Run': {'validate': 'ndis_crm.phase37_recovery_preparation.validate_recovery_preparation_run',
                                       'on_update': 'ndis_crm.phase37_recovery_preparation.on_recovery_preparation_run_update'},
 'NDIS CRM Recovery Case Draft Run': {'validate': 'ndis_crm.phase38_recovery_case_draft.validate_recovery_case_draft_run',
                                      'on_update': 'ndis_crm.phase38_recovery_case_draft.on_recovery_case_draft_run_update'},
 'NDIS Recovery Case': {'before_submit': 'ndis_crm.phase39_recovery_case_submission.validate_optional_recovery_case_phase39_submit_guard'},
 'NDIS CRM Recovery Case Submission Run': {'validate': 'ndis_crm.phase39_recovery_case_submission.validate_recovery_case_submission_run',
                                           'on_update': 'ndis_crm.phase39_recovery_case_submission.on_recovery_case_submission_run_update'},
 'NDIS CRM Recovery Follow Up Preparation Run': {'validate': 'ndis_crm.phase40_recovery_follow_up_preparation.validate_recovery_follow_up_preparation_run',
                                                 'on_update': 'ndis_crm.phase40_recovery_follow_up_preparation.on_recovery_follow_up_preparation_run_update'},
 'NDIS CRM Recovery Follow Up Task Draft Run': {'validate': 'ndis_crm.phase41_recovery_follow_up_task_draft.validate_recovery_follow_up_task_draft_run',
                                                'on_update': 'ndis_crm.phase41_recovery_follow_up_task_draft.on_recovery_follow_up_task_draft_run_update'},
 'ToDo': {'validate': 'ndis_crm.phase50_recovery_outcome_action_completion.validate_optional_phase50_todo_guard'},
 'Task': {'validate': 'ndis_crm.phase50_recovery_outcome_action_completion.validate_optional_phase50_task_guard'},
 'NDIS CRM Recovery Follow Up Task Activation Run': {'validate': 'ndis_crm.phase42_recovery_follow_up_task_activation.validate_recovery_follow_up_task_activation_run',
                                                     'on_update': 'ndis_crm.phase42_recovery_follow_up_task_activation.on_recovery_follow_up_task_activation_run_update'},
 'NDIS CRM Recovery Communication Draft Preparation Run': {'validate': 'ndis_crm.phase43_recovery_communication_draft_preparation.validate_recovery_communication_draft_preparation_run',
                                                           'on_update': 'ndis_crm.phase43_recovery_communication_draft_preparation.on_recovery_communication_draft_preparation_run_update'},
 'NDIS CRM Recovery Communication Draft Creation Run': {'validate': 'ndis_crm.phase44_recovery_communication_draft_creation.validate_recovery_communication_draft_creation_run',
                                                        'on_update': 'ndis_crm.phase44_recovery_communication_draft_creation.on_recovery_communication_draft_creation_run_update'},
 'Communication': {'validate': 'ndis_crm.phase45_recovery_communication_dispatch.validate_optional_phase45_communication_guard'},
 'NDIS CRM Recovery Communication Dispatch Run': {'validate': 'ndis_crm.phase45_recovery_communication_dispatch.validate_recovery_communication_dispatch_run',
                                                  'on_update': 'ndis_crm.phase45_recovery_communication_dispatch.on_recovery_communication_dispatch_run_update'},
 'NDIS CRM Recovery Communication Outcome Capture Run': {'validate': 'ndis_crm.phase46_recovery_communication_outcome_capture.validate_recovery_communication_outcome_capture_run',
                                                         'on_update': 'ndis_crm.phase46_recovery_communication_outcome_capture.on_recovery_communication_outcome_capture_run_update'},
 'NDIS CRM Recovery Outcome Action Preparation Run': {'validate': 'ndis_crm.phase47_recovery_outcome_action_preparation.validate_recovery_outcome_action_preparation_run',
                                                      'on_update': 'ndis_crm.phase47_recovery_outcome_action_preparation.on_recovery_outcome_action_preparation_run_update'},
 'NDIS CRM Recovery Outcome Action Draft Run': {'validate': 'ndis_crm.phase48_recovery_outcome_action_draft.validate_recovery_outcome_action_draft_run',
                                                'on_update': 'ndis_crm.phase48_recovery_outcome_action_draft.on_recovery_outcome_action_draft_run_update'},
 'NDIS CRM Recovery Outcome Action Activation Run': {'validate': 'ndis_crm.phase49_recovery_outcome_action_activation.validate_recovery_outcome_action_activation_run',
                                                     'on_update': 'ndis_crm.phase49_recovery_outcome_action_activation.on_recovery_outcome_action_activation_run_update'},
 'NDIS CRM Recovery Outcome Action Completion Run': {'validate': 'ndis_crm.phase50_recovery_outcome_action_completion.validate_recovery_outcome_action_completion_run',
                                                     'on_update': 'ndis_crm.phase50_recovery_outcome_action_completion.on_recovery_outcome_action_completion_run_update'},
 'NDIS CRM Recovery Outcome Closure Preparation Run': {'validate': 'ndis_crm.phase51_recovery_outcome_closure_preparation.validate_recovery_outcome_closure_preparation_run',
                                                       'on_update': 'ndis_crm.phase51_recovery_outcome_closure_preparation.on_recovery_outcome_closure_preparation_run_update'},
 'NDIS CRM Post Closure Routing Finalisation Run': {'validate': 'ndis_crm.phase55_post_closure_routing_finalisation.validate_post_closure_routing_finalisation_run',
                                                    'on_update': 'ndis_crm.phase55_post_closure_routing_finalisation.on_post_closure_routing_finalisation_run_update'},
 'NDIS CRM Care Management Integration Run': {'validate': 'ndis_crm.phase56_care_management_integration.validate_care_management_integration_run',
                                              'on_update': 'ndis_crm.phase56_care_management_integration.on_care_management_integration_run_update'},
 'NDIS CRM Operational Dashboard Snapshot Run': {'validate': 'ndis_crm.phase57_operational_dashboard_snapshot.validate_operational_dashboard_snapshot_run',
                                                 'on_update': 'ndis_crm.phase57_operational_dashboard_snapshot.on_operational_dashboard_snapshot_run_update'},
 'NDIS CRM Permission Workflow Hardening Run': {'validate': 'ndis_crm.phase58_permission_workflow_hardening.validate_permission_workflow_hardening_run',
                                                'on_update': 'ndis_crm.phase58_permission_workflow_hardening.on_permission_workflow_hardening_run_update'},
 'NDIS CRM Recovery Outcome Closure Draft Run': {'validate': 'ndis_crm.phase52_recovery_outcome_closure_draft.validate_recovery_outcome_closure_draft_run',
                                                 'on_update': 'ndis_crm.phase52_recovery_outcome_closure_draft.on_recovery_outcome_closure_draft_run_update'},
 'NDIS CRM UAT Regression Evidence Pack Run': {'validate': 'ndis_crm.phase59_uat_regression_evidence_pack.validate_uat_regression_evidence_pack_run',
                                               'on_update': 'ndis_crm.phase59_uat_regression_evidence_pack.on_uat_regression_evidence_pack_run_update'},
 'NDIS CRM Production Readiness Freeze Run': {'validate': 'ndis_crm.phase60_production_readiness_freeze.validate_production_readiness_freeze_run',
                                              'on_update': 'ndis_crm.phase60_production_readiness_freeze.on_production_readiness_freeze_run_update'}}
